services:
  svc-notification:
    image: janafinancial.azurecr.io/notification
    container_name: svc-notification
    hostname: svc-notification
    restart: unless-stopped
    expose:
      - 80
    networks:
      - npm
    labels:
      - com.centurylinklabs.watchtower.enable=true



networks:
  npm:
    external: true
