services:
  svc-faq:
    image: janafinancial.azurecr.io/faq
    container_name: svc-faq
    hostname: svc-faq
    restart: unless-stopped
    expose:
      - 80
    networks:
      - npm
    labels:
      - com.centurylinklabs.watchtower.enable=true



networks:
  npm:
    external: true
